version: 2
updates:
  # NPM dependencies - weekly, minor + path grouped
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    ignore:
      - dependency-name: '@playwright/test'
        update-types:
          - 'version-update:semver-patch'
          - 'version-update:semver-minor'
          - 'version-update:semver-major'
    # Groups define how Dependabot creates PRs for different update types
    groups:
      # minor + patch updates in one PR
      # applies-to is version updated by default so does not need to be specified
      minor-and-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
          
  # GitHub Actions - PRs only, no auto-updates
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
